---
title: 'HW 1 #4 question'
author: "Patrick Chase"
date: "2/7/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
sclass <- read.csv("https://raw.githubusercontent.com/jgscott/ECO395M/master/data/sclass.csv")
head(sclass)


```

```{r}
library(parallel)
library(caret) 
library(foreach)
library(FNN)
library(rsample)
library(modelr)

df350 <- sclass %>% 
  filter(trim == 350)%>%
  summarize(mileage = mileage,
            price = price)
head(df350)
```



```{r}
```


```{r}
k_val = c(2, 4, 6, 8, 10, 15, 20, 25, 30, 35, 40, 45,
           50, 60, 70, 80, 90, 100, 125, 150, 175, 200, 250, 300)
df350_out = foreach(i=1:20, .combine='rbind') %dopar% {
  df350_split = initial_split(df350, prop = .8)
  df350_train = training(df350_split)
  df350_test = testing(df350_split)
  rmse350 = foreach(k = k_val, .combine = 'c') %do% {
  model350 = knnreg(price ~ mileage, data = df350_train, k = k, use.all = TRUE)
  modelr:: rmse(model350, df350_test)
  }
  data.frame(k=k_val, rmse=rmse350) 
}
df350_out = arrange(df350_out, k)
```


```{r}
ggplot(df350_out) + geom_boxplot(aes(x=factor(k), y=rmse)) + theme_bw(base_size=7)
```

```{r}
df350_split = initial_split(df350, prop = .8)
  df350_train = training(df350_split)
  df350_test = testing(df350_split)
  
predicted350 <- knnreg(price ~ mileage, data = df350_train, k=15)
modelr::rmse(predicted350, df350_test)

```

```{r}
ggplot(data = df350) +
  geom_point(mapping = aes(x=mileage, y=price), color='lightgrey')+ geom_smooth(mapping = aes())
```









































